config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :answers
  resources :questions
  resources :quizzes
  resources :notices
  resources :timetables
  resources :syllabuses
  resources :contents
 
  resources :assingments do 
    resources :studentassingments
  end
  resources :studentprofiles  
  resources :profiles
  resources :createclasses
  resources :joins
  get 'main/index'
  get 'createclass/index'
  root 'home#index'
  devise_for :students
  devise_for :teachers
  get 'notice ', to: 'notices#unread'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
 
end

app/models/assingment.rb
class Assingment < ApplicationRecord
 belongs_to :createclass 
 has_many :studentassingments
 has_many_attached :file
 has_rich_text :instruction
end

app/models/content.rb
class Content < ApplicationRecord
  has_rich_text :description
  has_many_attached :file
  belongs_to :createclass
end

app/models/createclass.rb
class Createclass < ApplicationRecord
  belongs_to :teacher 
  has_and_belongs_to_many :students
  
  has_many :assingments
  has_many :contents
  has_many :syllabuses
  has_many :timetables
  has_many :notices
  has_many :quizzes
  #has_many :assingments, through: :studentassingments
end

app/models/join.rb
class Join < ApplicationRecord

  
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
  has_rich_text :massege

  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :teacher 
  mount_uploader :image, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :createclass
  has_many :questions
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

 has_and_belongs_to_many :createclasses
 has_one :studentprofile   

 
end

app/models/studentprofile.rb
class Studentprofile < ApplicationRecord
  belongs_to :student
  mount_uploader :image, FileUploader 
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :createclasses  
  has_one :profile   
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
    @profiles = Profile.all
  end

  # GET /contents/1 or /contents/1.json
  def show
    @profiles = Profile.all
    @studentprofiles = Studentprofile.all
    @createclass = Createclass.find(params[:id])
    @teachers = @createclass.teacher
  end

  # GET /contents/new
  def new
    @content = Content.new
    @profiles = Profile.all
  end

  # GET /contents/1/edit
  def edit
    @profiles = Profile.all
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

   

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:title, :description, :link, :file, :createclass_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_helper.rb
module JoinHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Title:</strong>
    <%= content.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= content.description %>
  </p>

  <p>
    <strong>Link:</strong>
    <a href="<%= content.link %>"><%= content.link %></a>
  </p>

  <p>
     <% if content.file.attached?%>
        <% content.file.each do |attachment| %>
         <% if attachment.image? %>
           <%= image_tag attachment, width: "200px"%>
         <% elsif attachment.video? %>
            <video width="320" height="240" controls>
              <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
            </video>
          <% else %>  
             <iframe src="<%= rails_blob_url(attachment) %>" width="100%" height="500px">
             </iframe>
         <% end %>  
        <% end %>
      <% end %>
    <p>

</div>

app/views/contents/_form.html.erb
<style>
  body {
      font-family: 'Lato', sans-serif
  }

  h1 {
      margin-bottom: 40px
  }

  label {
      color: #333
  }

  .btn-send {
      font-weight: 300;
      text-transform: uppercase;
      letter-spacing: 0.2em;
      width: 80%;
      margin-left: 3px
  }

  .help-block.with-errors {
      color: #ff5050;
      margin-top: 5px
  }

  .card {
      margin-left: 10px;
      margin-right: 10px
  }
</style>


<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container"> <div class=" text-center mt-5 "> 
          <h1>New Material</h1>
      </div>
      <div class="row ">
          <div class="col-lg-10 mx-auto">
              <div class="card mt-2 mx-auto p-4 " style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <div>
                <%= link_to "",  createclasses_path, class:"btn-close" %>
              </div>

                  <div class="card-body">
                      <div class="container">
                          <form id="contact-form" role="form">
                              <div class="controls">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="form-group"> <label for="form_name">Title *</label> 
                                          <%= form.text_field :title, class:"form-control", id:"form_name" , placeholder:"Please enter your Title", required:"required"  %>
                                          </div> <br>
                                      </div>
                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_lastname">Link </label>
                                          <%= form.url_field :link, class:"form-control", id:"form_name" , placeholder:"Please enter your Link"  %>
                                          </div>
                                      </div>
                                      <div class="col-md-12"> 
                                          <div class="form-group"> <label for="form_lastname">Description </label> 
                                          <%= form.rich_text_area :description, class:"form-control", id:"form_name" , placeholder:"Please enter your Description"  %>
                                          </div><br>
                                      </div>
                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_lastname">File </label> 
                                          <%= form.file_field :file, class:"form-control", id:"form_name" , placeholder:"Please enter your File"  %>
                                          </div>
                                      </div>
                                      <div class="col-md-6"> 
                                            <div class="form-group">
                                                <%= form.label :classes, class: 'control-group'%>
                                                <div class="form-control">
                                                  <%= collection_select( :content, :createclass_id, current_teacher.createclasses, :id, :classname, {}, {:multiple => false} )  %>
                                                </div>
                                           
                                          </div>
                                      </div>
                                  </div><br>
                                      
                                      <div class="text-center" >
                                        <%= form.submit 'create Material',  class:"btn btn-primary col-md-4", style:"box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;"  %>
                                      </div>

                              </div>
                          </form>
                      </div>
                  </div>
              </div> <!-- /.8 -->
          </div> <!-- /.row-->
      </div>
  </div>
  <% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/index.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<style>


.card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
        border-style:solid;
}

.card:hover {
  background-color:#DAE3F2;
}

.icon2{
  background-color: #F5731A;
  border-radius: 50%;
  width:50px;
  height:50px;
  margin-top:12px;
  float:left;
}
.savg{
  margin: 15px 15px 15px 13px;
  color:#fff;
}
</style>







<div id="contents">
  <% @contents.each do |content| %>
    <div class="card"  style="width: 45rem;">
   <%= link_to(content) do %>
      <div class="card-body ">
         <div class="icon2">
          <i class="material-icons savg">&#xe85d;</i>
         </div><br>
         <p style="color:black;">&nbsp;
           <%= current_teacher.name.upcase%>
                 posted a new material:
            <%= content.title.capitalize %><br>
            &nbsp;<%= content.created_at.strftime("%d  %B, %Y") %>
           
         </p>

      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/contents/new.html.erb
<%= render "form", content: @content %>

<br>

app/views/contents/show.html.erb
<style>

  hr {
    border: none;
    border-top: 2px double blue;
    color: blue;
    overflow: visible;
    text-align: center;
    height: 5px;
    margin-left:120px;
    margin-right:120px;
}

hr:after {
    background: #fff;
    content: '§';
    padding: 0 4px;
    position: relative;
    top: -13px;
}

.mtr{
  margin-left:120px;
}

h3{
  color:blue;
}

</style>

<br>
<br>

<div class="mtr">
<h3>
<%= @content.title.capitalize%>
</h3>
<% if teacher_signed_in? %>
  <%= current_teacher.name.upcase%> - <%= @content.created_at.strftime("%d  %B, %Y")%>
<% end %>
<% if student_signed_in? %>
  <%= @teachers.name.upcase%> - <%= @content.created_at.strftime("%d  %B, %Y")%>
<% end %>
</div>

<% if teacher_signed_in? %>
<div class="dropdown" style="float:right; margin-right:125px; margin-top:-25px;">

  <i class="fa fa-ellipsis-v" style="font-size:30px; color:blue;" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></i>
  
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "Edit", edit_content_path(@content) , class:"dropdown-item" %></li>
    <li><%= button_to "Destroy this content", @content, method: :delete , class:"dropdown-item" %></li>
  </ul>
</div>
<% end %>
<hr>

<div class="card container" >
  <div class="card-body">
    <%= @content.description%>
  </div>
</div>
<br>
<% if @content.link.present?%>
<div id="contents">
    <div class="card container"  style="width: 44rem; height:80px;">
      <div class="card-body">
         <i class="fa fa-link" style="font-size:36px; color:#88c2d5;"></i>
         <a href="<%= @content.link %>"><%= @content.link %></a>
      </div>
    </div>
</div>
<% end %>
<% if @content.file.attached?%>
<div class="card container"  style="width: 44rem; height:80px;">
    <div class="card-body">
        <div data-bs-toggle="modal" data-bs-target="#example">
                <% @content.file.each do |attachment| %>
                <% if attachment.image? %>
                  <%= image_tag attachment, width: "100px"%>
                <% elsif attachment.video? %>
                    <video width="100px" height="60" controls>
                      <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
                    </video>
                  <% else %>  
                    <iframe src="<%= rails_blob_url(attachment) %>" width="100px" height="50px">
                    </iframe>
                <% end %>  
                <% end %>
             show this material
            <% end %>
        </div>
   </div>  
</div>

<div class="modal fade" id="example" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pepole</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <% if @content.file.attached?%>
        <% @content.file.each do |attachment| %>
         <% if attachment.image? %>
           <%= image_tag attachment, width: "1000px"%>
         <% elsif attachment.video? %>
            <video width="800" height="400" controls>
              <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
            </video>
          <% else %>  
             <iframe src="<%= rails_blob_url(attachment) %>" width="1000px" height="500px">
             </iframe>
         <% end %>  
        <% end %>
      <% end %>
      </div>
      
    </div>
  </div>
</div>