config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :answers
  resources :questions
  resources :quizzes
  resources :notices
  resources :timetables
  resources :syllabuses
  resources :contents
 
  resources :assingments do 
    resources :studentassingments
  end
  resources :studentprofiles  
  resources :profiles
  resources :createclasses
  resources :joins
  get 'main/index'
  get 'createclass/index'
  root 'home#index'
  devise_for :students
  devise_for :teachers
  get 'notice ', to: 'notices#unread'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
 
end

app/models/assingment.rb
class Assingment < ApplicationRecord
 belongs_to :createclass 
 has_many :studentassingments
 has_many_attached :file
 has_rich_text :instruction
end

app/models/content.rb
class Content < ApplicationRecord
  has_rich_text :description
  has_many_attached :file
  belongs_to :createclass
end

app/models/createclass.rb
class Createclass < ApplicationRecord
  belongs_to :teacher 
  has_and_belongs_to_many :students
  
  has_many :assingments
  has_many :contents
  has_many :syllabuses
  has_many :timetables
  has_many :notices
  has_many :quizzes
  #has_many :assingments, through: :studentassingments
end

app/models/join.rb
class Join < ApplicationRecord

  
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
  has_rich_text :massege

  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :teacher 
  mount_uploader :image, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :createclass
  has_many :questions
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

 has_and_belongs_to_many :createclasses
 has_one :studentprofile   

 
end

app/models/studentprofile.rb
class Studentprofile < ApplicationRecord
  belongs_to :student
  mount_uploader :image, FileUploader 
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :createclasses  
  has_one :profile   
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: %i[ show edit update destroy ]
  
  # GET /notices or /notices.json
  def index
    @notices = Notice.all
    @profiles = Profile.all
  end

  # GET /notices/1 or /notices/1.json
  def show
    @profiles = Profile.all
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    @profiles = Profile.all
  end

  # GET /notices/1/edit
  def edit
    @profiles = Profile.all
  end

  # POST /notices or /notices.json
  def create
    @profiles = Profile.all
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to createclasses_url(@notice), notice: "Notice was successfully created." }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /notices/1 or /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to notice_url(@notice), notice: "Notice was successfully updated." }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1 or /notices/1.json
  def destroy
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url, notice: "Notice was successfully destroyed." }
      format.json { head :no_content }
    end
  end
 
  def unread
    #logic to add a friend
    notice = Notice.find(params[:id])
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:massege, :file , :createclass_id , :read)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_helper.rb
module JoinHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/notices/_form.html.erb
<style>
  body {
      font-family: 'Lato', sans-serif
  }

  h1 {
      margin-bottom: 40px
  }

  label {
      color: #333
  }

  .btn-send {
      font-weight: 300;
      text-transform: uppercase;
      letter-spacing: 0.2em;
      width: 80%;
      margin-left: 3px
  }

  .help-block.with-errors {
      color: #ff5050;
      margin-top: 5px
  }

  .card {
      margin-left: 10px;
      margin-right: 10px
  }
</style>


<%= form_with(model: notice) do |form| %>
  <% if notice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
        <% notice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container"> <div class=" text-center mt-5 "> 
          <h1>New Notic</h1>
      </div>
      <div class="row ">
          <div class="col-lg-10 mx-auto">
              <div class="card mt-2 mx-auto p-4 " style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <div>
                <%= link_to "",  createclasses_path, class:"btn-close" %>
              </div>

                  <div class="card-body">
                      <div class="container">
                          <form id="contact-form" role="form">
                              <div class="controls">
                                  <div class="row">
                                      
                                      <div class="col-md-12"> 
                                          <div class="form-group"> <label for="form_lastname">Massege </label> 
                                          <%= form.rich_text_area :massege, class:"form-control", id:"form_name" , placeholder:"Please enter your Massege"  %>
                                          </div><br>
                                      </div>
                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_lastname">File </label> 
                                          <%= form.file_field :file, class:"form-control", id:"form_name" , placeholder:"Please enter your File"  %>
                                          </div>
                                      </div>
                                      <div class="col-md-6"> 
                                            <div class="form-group">
                                                <%= form.label :classes, class: 'control-group'%>
                                                <div class="form-control">
                                                  <%= collection_select( :notice, :createclass_id, current_teacher.createclasses, :id, :classname, {}, {:multiple => false} )  %>
                                                </div>
                                           
                                          </div>
                                      </div>
                                  </div><br>
                                      
                                      <div class="text-center" >
                                        <%= form.submit 'create Notic',  class:"btn btn-primary col-md-4", style:"box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;"  %>
                                      </div>

                              </div>
                          </form>
                      </div>
                  </div>
              </div> <!-- /.8 -->
          </div> <!-- /.row-->
      </div>
  </div>
  <% end %>

app/views/notices/_notice.html.erb
<div id="<%= dom_id notice %>">
   <div class="alert alert-danger" role="alert"><%= notice.massege %></div>
  <p>
     <% if notice.file.attached?%>
        <% notice.file.each do |attachment| %>
         <% if attachment.image? %>
           <%= image_tag attachment, width: "1000px"%>
         <% elsif attachment.video? %>
            <video width="320" height="240" controls>
              <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
            </video>
          <% else %>  
             <iframe src="<%= rails_blob_url(attachment) %>" width="100%" height="500px">
             </iframe>
         <% end %>  
        <% end %>
      <% end %>
    <p>

</div>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render "form", notice: @notice %>

<br>

<div>
  <%= link_to "Show this notice", @notice %> |
  <%= link_to "Back to notices", notices_path %>
</div>

app/views/notices/index.html.erb
<div id="notices">
  <% @notices.each do |notice| %>
    <%= render notice %>
    <p>
      <%= link_to "Show this notice", notice %>
    </p>
  <% end %>
</div>

<%= link_to "New notice", new_notice_path %>

app/views/notices/new.html.erb
<%= render "form", notice: @notice %>

<br>

<%# <div>
  <%= link_to "Back to notices", notices_path %>
<%# </div>  %>

app/views/notices/show.html.erb
<br>
<br>
<br>


<%= render @notice %>

<div>
  <%= link_to "Edit this notice", edit_notice_path(@notice) %> |
  <%= link_to "Back to class", createclasses_path %>

  <%= button_to "Destroy this notice", @notice, method: :delete %>
</div>