config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :answers
  resources :questions
  resources :quizzes
  resources :notices
  resources :timetables
  resources :syllabuses
  resources :contents
 
  resources :assingments do 
    resources :studentassingments
  end
  resources :studentprofiles  
  resources :profiles
  resources :createclasses
  resources :joins
  get 'main/index'
  get 'createclass/index'
  root 'home#index'
  devise_for :students
  devise_for :teachers
  get 'notice ', to: 'notices#unread'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
 
end

app/models/assingment.rb
class Assingment < ApplicationRecord
 belongs_to :createclass 
 has_many :studentassingments
 has_many_attached :file
 has_rich_text :instruction
end

app/models/content.rb
class Content < ApplicationRecord
  has_rich_text :description
  has_many_attached :file
  belongs_to :createclass
end

app/models/createclass.rb
class Createclass < ApplicationRecord
  belongs_to :teacher 
  has_and_belongs_to_many :students
  
  has_many :assingments
  has_many :contents
  has_many :syllabuses
  has_many :timetables
  has_many :notices
  has_many :quizzes
  #has_many :assingments, through: :studentassingments
end

app/models/join.rb
class Join < ApplicationRecord

  
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
  has_rich_text :massege

  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :teacher 
  mount_uploader :image, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :createclass
  has_many :questions
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

 has_and_belongs_to_many :createclasses
 has_one :studentprofile   

 
end

app/models/studentprofile.rb
class Studentprofile < ApplicationRecord
  belongs_to :student
  mount_uploader :image, FileUploader 
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :createclasses  
  has_one :profile   
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profiles = Profile.all
    @studentprofiles = Studentprofile.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_helper.rb
module JoinHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/home/_fotter.html.erb
<style>

@import url('https://fonts.googleapis.com/css?family=Rubik&display=swap');

 /* body {
     font-family: 'Rubik', sans-serif;
     height: 100% !important;
     background-color: #F8F9FB !important
 } */

 .container-fluid {
     margin-top: 101px;
     color: #000 !important
 }

 .card {
     background-color: #F8F9FB !important
 }

 p {
     font-size: calc(12px + (14 - 12) * ((100vw - 360px) / (1600 - 360))) !important;
     display: fkex
 }

 h3 {
     font-size: calc(24px + (30 - 24) * ((100vw - 360px) / (1600 - 360))) !important
 }

 .social {
     font-size: 21px !important
 }

 .color-text {
     color: #757575 !important
 }

 button {
     font-size: calc(12px + (13 - 12) * ((100vw - 360px) / (1600 - 320))) !important;
     background-color: #2CA6FB !important;
     padding-left: calc(20px + (28 - 20) * ((100vw - 360px) / (1600 - 360))) !important;
     padding-right: calc(20px + (28 - 20) * ((100vw - 360px) / (1600 - 360))) !important;
     padding-top: calc(10px + (12 - 10) * ((100vw - 360px) / (1600 - 360))) !important;
     padding-bottom: calc(10px + (12 - 10) * ((100vw - 360px) / (1600 - 360))) !important
 }

 button:focus {
     -moz-box-shadow: none !important;
     -webkit-box-shadow: none !important;
     box-shadow: none !important;
     outline-width: 0
 }

 footer {
     color: #caced1 !important
 }

 li {
     margin-top: 20px;
     margin-bottom: 20px
 }

 .Careers {
     cursor: pointer;
     color: #1E88E5
 }

 .row-1 {
     background-color: #1E242A !important
 }

 .row-2 {
     background-color: #28323C !important
 }
</style>


<div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
    <div class="row my-5 justify-content-center">
        <div class="col text-center">
            <div class="card border-0">
                <div class="card-body">
                    <div class="card-title">
                        <h3 class="mb-4">Ready to See What your team can do?</h3>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-4 col">
                            <p class="small color-text">We'll show you how your team can have more meaningful conservations with your customers without heavy IT effors. </p> <button type="button" class="btn btn-primary border-0 my-4"><b>Get in Touch</b></button><br> <img src="https://i.imgur.com/pC6AgYC.jpg" class="img-fluid" width="450">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="row justify-content-center mb-0 pt-5 pb-0 row-2 px-3">
            <div class="col-12">
                <div class="row row-2">
                    <div class="col-sm-3 text-md-center">
                        <h5><span> <i class="fa fa-magnet "  style="color:#07d8ff;"></i>&nbsp<i class="fa fa-ellipsis-v " aria-hidden="true" style="color:red;"></i></span><b> University Based <br> Class Managment</b></h5>
                    </div>
                    <div class="col-sm-3 my-sm-0 mt-5">
                        <ul class="list-unstyled">
                            <li class="mt-0">Platform</li>
                            <li>Help Center</li>
                            <li>Security</li>
                        </ul>
                    </div>
                    <div class="col-sm-3 my-sm-0 mt-5">
                        <ul class="list-unstyled">
                            <li class="mt-0">Customers</li>
                            <li>Use Cases</li>
                            <li>Customers Services</li>
                        </ul>
                    </div>
                    <div class="col-sm-3 my-sm-0 mt-5">
                        <ul class="list-unstyled">
                            <li class="mt-0">Company</li>
                            <li>About</li>
                            <li>Careers- <span class="Careers">We're-hiring</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-0 pt-0 row-1 mb-0 px-sm-3 px-2">
            <div class="col-12">
                <div class="row my-4 row-1 no-gutters">
                    <div class="col-sm-3 col-auto text-center"><small>&#9400; Stride Softwere</small></div>
                    <div class="col-md-3 col-auto "></div>
                    <div class="col-md-3 col-auto"></div>
                    <div class="col my-auto text-md-left text-right "> <small> hello@getstride.com <span><img src="https://i.imgur.com/TtB6MDc.png" class="img-fluid " width="25"></span> <span><img src="https://i.imgur.com/N90KDYM.png" class="img-fluid " width="25"></span></small> </div>
                </div>
            </div>
        </div>
    </footer>
</div>

app/views/home/_header.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
 <%# <style>
.logo1{
  height:28;
}
</style>  %>


<body>

  <!-- ======= Header ======= -->
  
  <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center">
        <i class="fa fa-magnet" style="font-size:48px;color:#07d8ff"></i>&nbsp;&nbsp;
        <i class="fa fa-ellipsis-v" style="font-size:48px;color:red"></i>&nbsp;
        <h1 class="logo me-auto"><a href="">University Based  Class Management</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar">
        <ul>
        <% if teacher_signed_in?%>
        <li class="nav-link scrollto">
          
        <li class="nav-link scrollto">
           <%= link_to 'Home',  createclasses_path,class:"nav-link"%>
        </li>  
        
        <% if current_teacher.profile.present?%>

         
         <% @profiles.each do |profile| %>
        
          <% if profile.teacher == current_teacher%>
            <img src="<%= profile.image %>" class="rounded-circle account-img" alt="..." style="width: 45px; height: 45px;">
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" style="color:#fff;" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"> <%= current_teacher.name.capitalize %></button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Profile", profile ,class:"dropdown-item" %></li>
                <li><%= button_to('Logout',  destroy_teacher_session_path, :method => :delete , class:"dropdown-item" )%> </li>
              </ul>
            </div>
              
        <% end %>
        <% end %>
        <% else %> 
         <li class="nav-link scrollto"> 
          <%= link_to(new_profile_path) do %>
            <%= image_tag "profile2.jpeg" ,class:'rounded-circle account-img',style: 'width: 45px; height: 45px;' %>
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" style="color:#fff;" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"> <%= current_teacher.name.capitalize %></button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= button_to('Logout',  destroy_teacher_session_path, :method => :delete , class:"dropdown-item" )%> </li>
                 <li><%= button_to('Add Profile' , new_profile_path , class:"dropdown-item" )%> 
              </ul>
            </div>
          <% end %>
          <% end %> 
         </li>  
        
         
         
        </li>
       <% else %> 

       <% if student_signed_in?%>
          <li class="nav-link scrollto">
           <%= link_to 'Home',  joins_path,class:"nav-link"%>
        </li>  
        
        <% if current_student.studentprofile.present?%>

         
         <% @studentprofiles.each do |studentprofile| %>
        
          <% if studentprofile.student == current_student%>
            <img src="<%= studentprofile.image %>" class="rounded-circle account-img" alt="..." style="width: 45px; height: 45px;">
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" style="color:#fff;" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"> <%= current_student.name.capitalize %></button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Profile", studentprofile ,class:"dropdown-item" %></li>
                <li><%= button_to('Logout',  destroy_student_session_path, :method => :delete , class:"dropdown-item" )%> </li>
              </ul>
            </div>
              
        <% end %>
        <% end %>
        <% else %> 
         <li class="nav-link scrollto"> 
          <%= link_to(new_studentprofile_path) do %>
            <%= image_tag "profile2.jpeg" ,class:'rounded-circle account-img',
            style: 'width: 45px; height: 45px;' %>
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" style="color:#fff;" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"> <%= current_student.name.capitalize %></button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= button_to('Logout',  destroy_student_session_path, :method => :delete , class:"dropdown-item" )%> 
                <li><%= button_to('Add Profile', new_studentprofile_path ,class:"dropdown-item" )%></li>
              </ul>
            </div>
          <% end %>
          <% end %> 
         </li>  
        <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sing_up
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Teacher' , new_teacher_registration_path, class:"dropdown-item"%></li>
            <li><%= link_to 'Student' , new_student_registration_path, class:"dropdown-item"%></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sing_in
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Teacher' , new_teacher_session_path, class:"dropdown-item"%></li>
            <li><%= link_to 'Student' , new_student_session_path, class:"dropdown-item"%></li>
          </ul>
        </li>
       <% end %>
        <% end %>
          </ul>  
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->
          
         

  
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/chart.js/chart.min.js"></script>
  <script src="assets/vendor/echarts/echarts.min.js"></script>
  <script src="assets/vendor/quill/quill.min.js"></script>
  <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>
 <br>
 <br>
 <br>