config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :answers
  resources :questions
  resources :quizzes
  resources :notices
  resources :timetables
  resources :syllabuses
  resources :contents
 
  resources :assingments do 
    resources :studentassingments
  end
  resources :studentprofiles  
  resources :profiles
  resources :createclasses
  resources :joins
  get 'main/index'
  get 'createclass/index'
  root 'home#index'
  devise_for :students
  devise_for :teachers
  get 'notice ', to: 'notices#unread'
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
 
end

app/models/assingment.rb
class Assingment < ApplicationRecord
 belongs_to :createclass 
 has_many :studentassingments
 has_many_attached :file
 has_rich_text :instruction
end

app/models/content.rb
class Content < ApplicationRecord
  has_rich_text :description
  has_many_attached :file
  belongs_to :createclass
end

app/models/createclass.rb
class Createclass < ApplicationRecord
  belongs_to :teacher 
  has_and_belongs_to_many :students
  
  has_many :assingments
  has_many :contents
  has_many :syllabuses
  has_many :timetables
  has_many :notices
  has_many :quizzes
  #has_many :assingments, through: :studentassingments
end

app/models/join.rb
class Join < ApplicationRecord

  
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
  has_rich_text :massege

  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :teacher 
  mount_uploader :image, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :createclass
  has_many :questions
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

 has_and_belongs_to_many :createclasses
 has_one :studentprofile   

 
end

app/models/studentprofile.rb
class Studentprofile < ApplicationRecord
  belongs_to :student
  mount_uploader :image, FileUploader 
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :createclasses  
  has_one :profile   
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  has_many_attached :file
  belongs_to :createclass
end

app/controllers/assingments_controller.rb
class AssingmentsController < ApplicationController
  before_action :set_assingment, only: %i[ show edit update destroy ]

  # GET /assingments or /assingments.json
  def index
    @assingments = Assingment.order(created_at: :desc)
    @profiles = Profile.all
    
  end

  # GET /assingments/1 or /assingments/1.json
  def show
    @studentassingments = @assingment.studentassingments.order(created_at: :desc)
    @profiles = Profile.all

    
  end

  # GET /assingments/new
  def new
    @assingment = Assingment.new
    @profiles = Profile.all
  end

  # GET /assingments/1/edit
  def edit
    @profiles = Profile.all
  end

  # POST /assingments or /assingments.json
  def create
    @assingment = Assingment.new(assingment_params)

    respond_to do |format|
      if @assingment.save
        format.html { redirect_to assingment_url(@assingment), notice: "Assingment was successfully created." }
        format.json { render :show, status: :created, location: @assingment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assingment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assingments/1 or /assingments/1.json
  def update
    respond_to do |format|
      if @assingment.update(assingment_params)
        format.html { redirect_to assingment_url(@assingment), notice: "Assingment was successfully updated." }
        format.json { render :show, status: :ok, location: @assingment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assingment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assingments/1 or /assingments/1.json
  def destroy
    @assingment.destroy

    respond_to do |format|
      format.html { redirect_to assingments_url, notice: "Assingment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assingment
      @assingment = Assingment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assingment_params
      params.require(:assingment).permit(:title, :points, :duedate, :topic, :createclass_id , :instruction , :file )
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/assingments_helper.rb
module AssingmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_helper.rb
module JoinHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/assingments/_assingment.html.erb
<div id="<%= dom_id assingment %>">
  <p>
    <strong>Title:</strong>
    <%= assingment.title %>
  </p>

  <p>
    <strong>Points:</strong>
    <%= assingment.points %>
  </p>

  <p>
    <strong>Duedate:</strong>
    <%= assingment.duedate %>
  </p>

  <p>
    <strong>Topic:</strong>
    <%= assingment.topic %>
  </p>

  <p>
    <strong>Iinstruction:</strong>
    <%= assingment.instruction %>
  </p>

   <p>
     <% if assingment.file.attached?%>
        <% assingment.file.each do |attachment| %>
         <% if attachment.image? %>
           <%= image_tag attachment, width: "200px"%>
         <% elsif attachment.video? %>
            <video width="320" height="240" controls>
              <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
            </video>
          <% else %>  
             <iframe src="<%= rails_blob_url(attachment) %>" width="100px" height="80px">
             </iframe>
         <% end %>  
        <% end %>
      <% end %>
    <p>

</div>

app/views/assingments/_form.html.erb
<%= form_with(model: assingment) do |form| %>
  <% if assingment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assingment.errors.count, "error") %> prohibited this assingment from being saved:</h2>

      <ul>
        <% assingment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container"> <div class=" text-center mt-5 "> 
          <h1>New Assingment</h1>
      </div>
      <div class="row ">
          <div class="col-lg-10 mx-auto">
              <div class="card mt-2 mx-auto p-4 " style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
              <div>
                <%= link_to "",  createclasses_path, class:"btn-close" %>
              </div>

                  <div class="card-body ">
                      <div class="container">
                          <form id="contact-form" role="form">
                              <div class="controls">
                                  <div class="row">
                                      <div class="col-md-6">
                                          <div class="form-group"> <label for="form_title">Title *</label> 
                                          <%= form.text_field :title, class:"form-control", id:"form_name" , placeholder:"Please enter your Title", required:"required"  %>
                                          </div>
                                      </div>
                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_points">Points *</label> 
                                          <%= form.number_field :points, class:"form-control", id:"form_name" , placeholder:"Please enter your Points", required:"required"  %>
                                          </div><br>
                                      </div>

                                      <div class="col-md-12"> 
                                          <div class="form-group"> <label for="form_lastname">Instruction </label> 
                                          <%= form.rich_text_area :instruction, class:"form-control", id:"form_name" , placeholder:"Please enter your Instruction (optional)"  %>
                                          </div>
                                      </div>

                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_duedate">DueDate *</label> 
                                          <%= form.date_field :duedate, class:"form-control", id:"form_name" , placeholder:"Please enter your DueDate", required:"required"  %>
                                          </div>
                                      </div>
                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_topic">Topic *</label> 
                                          <%= form.text_field :topic, class:"form-control", id:"form_name" , placeholder:"Please enter your Topic", required:"required"  %>
                                          </div><br>
                                      </div>

                                      <div class="col-md-6"> 
                                          <div class="form-group"> <label for="form_file">File </label> 
                                          <%= form.file_field :file, class:"form-control", id:"form_name" , placeholder:"Please enter your File"  %>
                                          </div>
                                      </div>

                                      <div class="col-md-6"> 
                                            <div class="form-group">
                                                <%= form.label :classes, class: 'control-group'%>
                                                <div class="form-control">
                                                  <%= collection_select( :assingment, :createclass_id, current_teacher.createclasses, :id, :classname, {}, {:multiple => false} )  %>
                                                </div>
                                           
                                          </div>
                                      </div>
                                  </div><br>
                                      
                                      <div class="text-center">
                                        <%= form.submit  class:"btn btn-success btn-send pt-2 btn-block col-md-6" %>
                                      </div>

                              </div>
                          </form>
                      </div>
                  </div>
              </div> <!-- /.8 -->
          </div> <!-- /.row-->
      </div>
  </div>
  <% end %>

app/views/assingments/edit.html.erb
<%= render "form", assingment: @assingment %>

<br>

<div>
  <%= link_to "Show this assingment", @assingment %> |
  <%= link_to "Back to assingments", assingments_path %>
</div>

app/views/assingments/index.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<style>
.card {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
        border-style:solid;
}

.card:hover {
  background-color:#DAE3F2;
}

.icon{
  background-color: #129eaf;
  border-radius: 50%;
  width:50px;
  height:50px;
  margin-top:12px;
  float:left;
}
.savg{
  margin: 15px 15px 15px 13px;
  color:#fff;
}
</style>






  <% @assingments.each do |assingment| %>
    <div class="card"  style="width: 45rem;">
   <%= link_to(assingment) do %>
      <div class="card-body ">
         <div class="icon">
          <i class="material-icons savg">&#xe85d;</i>
         </div><br>
         <p style="color:black;">&nbsp;
            <%= current_teacher.name.upcase%>
                 posted a new assingment:
            <%= assingment.title.capitalize %><br>
            &nbsp;<%= assingment.created_at.strftime("%d  %B, %Y")  %>
           
         </p>

      </div>
    </div>
    <% end %>
  <% end %>

app/views/assingments/new.html.erb
<%= render "form", assingment: @assingment %>

<br>

app/views/assingments/show.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>

 hr {
    border: none;
    border-top: 2px double blue;
    color: blue;
    overflow: visible;
    text-align: center;
    height: 5px;
    margin-left:120px;
    margin-right:120px;
}

hr:after {
    background: #fff;
    content: '§';
    padding: 0 4px;
    position: relative;
    top: -13px;
}

.mtr{
  margin-left:120px;
}

h3{
  color:blue;
}



</style>

<br>
<div class="mtr">
<i class="material-icons">&#xe85d;</i>
<h3>
<%= @assingment.title.capitalize%>
</h3>
<h4><%= @assingment.topic.capitalize%></h4>
<p> Point - <%= @assingment.points%></p>
<p> DueDate - <%= @assingment.duedate.strftime("%d  %B, %Y")%></p>
</div>

<% if teacher_signed_in? %>
<div class="dropdown" style="float:right; margin-right:125px; margin-top:-65px;">

  <i class="fa fa-ellipsis-v" style="font-size:30px; color:blue;" class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></i>
  
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "Edit", edit_assingment_path(@assingment) , class:"dropdown-item" %></li>
    <li><%= button_to "Destroy this content", @assingment, method: :delete , class:"dropdown-item" %></li>
  </ul>
</div>
<% end %>
<hr>
<% if teacher_signed_in? %>
  <p style="float:right; margin-top:-45px; margin-right:120px;"><%= current_teacher.name.upcase%> - <%= @assingment.created_at.strftime("%d  %B, %Y")%></p>
<% end %>
<% if student_signed_in? %>
 <p style="float:right; margin-top:-45px; margin-right:120px;"> <%= @teachers.name.upcase%> - <%= @assingment.created_at.strftime("%d  %B, %Y")%> </p>
<% end %>


<% if @assingment.instruction.present?%>
    <div class="card container" style="box-shadow: rgba(0, 0, 0, 0.4) 0px 2px 4px, rgba(0, 0, 0, 0.3) 0px 7px 13px -3px, rgba(0, 0, 0, 0.2) 0px -3px 0px inset;">
      <div class="card-body">
         <%= @assingment.instruction %>
      </div>
    </div>
<% end %>

<% if @assingment.file.attached?%>
<div class="card container"  style="width: 44rem; height:80px;">
    <div class="card-body">
        <div data-bs-toggle="modal" data-bs-target="#example">
                <% @assingment.file.each do |attachment| %>
                <% if attachment.image? %>
                  <%= image_tag attachment, width: "100px"%>
                <% elsif attachment.video? %>
                    <video width="100px" height="60" controls>
                      <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
                    </video>
                  <% else %>  
                    <iframe src="<%= rails_blob_url(attachment) %>" width="100px" height="50px">
                    </iframe>
                <% end %>  
                <% end %>
             show this material
            <% end %>
        </div>
   </div>  
</div>


<div class="modal fade" id="example" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pepole</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
         <% if @assingment.file.attached?%>
        <% @assingment.file.each do |attachment| %>
         <% if attachment.image? %>
           <%= image_tag attachment, width: "1000px"%>
         <% elsif attachment.video? %>
            <video width="800" height="400" controls>
              <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
            </video>
          <% else %>  
             <iframe src="<%= rails_blob_url(attachment) %>" width="1000px" height="500px">
             </iframe>
         <% end %>  
        <% end %>
      <% end %>
      </div>
      
    </div>
  </div>
</div>


<div>

   <%= render template: "studentassingments/index" %>

</div>


<div class="modal fade" id="exampl" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Student assingments</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <% @studentassingments.each do |studentassingment| %>

        <h5 style="color:blue; text-align:center;"> <b>Student Name</b> = <%= studentassingment.student_name %></h5>
          <% if @assingment.duedate < studentassingment.created_at%>
              <p style="color:red;">Missing</p>
          <% end %>
          <p style="text-align:center;">
            <% if studentassingment.file.attached?%>
              <% studentassingment.file.each do |attachment| %>
              <% if attachment.image? %>
                <%= image_tag attachment, width: "1000px"%>
              <% elsif attachment.video? %>
                  <video width="1000px" height="500" controls>
                    <source src="<%= rails_blob_url(attachment)%>" type="<%= attachment.content_type %>" />
                  </video>
                <% else %>  
                  <iframe src="<%= rails_blob_url(attachment) %>" width="100%" height="500px">
                  </iframe>
              <% end %>  
              <% end %>
            <% end %>
          </p>
      <hr>
      </div>
          <% end %>  
    </div>
  </div>
</div>